version: 0.0
os: linux
files:
  - source: /index.js
    destination: /moviesgit2.0/
  - source: /index.ejs
    destination: /moviesgit2.0/views/
hooks:
  BeforeInstall:
    - location: scripts/install_dependencies
      timeout: 300
      runas: root
    - location: scripts/start_server
      timeout: 300
      runas: root
  ApplicationStop:
    - location: scripts/stop_server
      timeout: 300
      runas: root
